Executing (default): CREATE TABLE IF NOT EXISTS `Categories` (`id` INTEGER UNSIGNED auto_increment , `slug` VARCHAR(255) NOT NULL, `image` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Categories` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `CategoryTrs` (`langCode` VARCHAR(255) , `name` VARCHAR(255) NOT NULL, `description` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `categoryId` INTEGER UNSIGNED , PRIMARY KEY (`langCode`, `categoryId`), FOREIGN KEY (`categoryId`) REFERENCES `Categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `CategoryTrs` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `Users` (`id` BIGINT UNSIGNED auto_increment , `username` VARCHAR(255) NOT NULL, `email` VARCHAR(255) NOT NULL, `fullname` VARCHAR(255) NOT NULL, `password` VARCHAR(255) NOT NULL, `birthdate` DATETIME NOT NULL, `sex` ENUM('MALE', 'FEMALE') NOT NULL, `biography` TEXT, `profileImage` VARCHAR(255) DEFAULT 'https://cdn.zhowit.com/users/default/profile.jpg', `coverImage` VARCHAR(255) DEFAULT 'https://cdn.zhowit.com/users/default/cover.jpg', `acceptTerms` TINYINT(1) NOT NULL, `langCode` VARCHAR(255) NOT NULL DEFAULT 'en', `postsCount` INTEGER UNSIGNED NOT NULL DEFAULT 0, `likesCount` INTEGER UNSIGNED NOT NULL DEFAULT 0, `dislikesCount` INTEGER UNSIGNED NOT NULL DEFAULT 0, `followingCount` INTEGER UNSIGNED NOT NULL DEFAULT 0, `followersCount` INTEGER UNSIGNED NOT NULL DEFAULT 0, `unreadedNotificationsCount` INTEGER UNSIGNED NOT NULL DEFAULT 0, `unreadedMessagesCount` INTEGER UNSIGNED NOT NULL DEFAULT 0, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME, UNIQUE `username` (`username`), UNIQUE `email` (`email`), PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Users` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `Posts` (`id` BIGINT UNSIGNED auto_increment , `title` VARCHAR(255) NOT NULL, `description` TEXT, `likesCount` INTEGER UNSIGNED NOT NULL DEFAULT 0, `dislikesCount` INTEGER UNSIGNED NOT NULL DEFAULT 0, `commentsCount` INTEGER UNSIGNED NOT NULL DEFAULT 0, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME, `userId` BIGINT UNSIGNED NOT NULL, `categoryId` INTEGER UNSIGNED NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`categoryId`) REFERENCES `Categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Posts` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `Comments` (`id` BIGINT UNSIGNED auto_increment , `comment` TEXT NOT NULL, `likesCount` INTEGER UNSIGNED NOT NULL DEFAULT 0, `dislikesCount` INTEGER UNSIGNED NOT NULL DEFAULT 0, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME, `userId` BIGINT UNSIGNED NOT NULL, `postId` BIGINT UNSIGNED NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`postId`) REFERENCES `Posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Comments` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `Languages` (`langCode` VARCHAR(255) , `name` VARCHAR(255) NOT NULL UNIQUE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME, UNIQUE `Languages_name_unique` (`name`), PRIMARY KEY (`langCode`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Languages` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `Messages` (`id` BIGINT UNSIGNED auto_increment , `message` VARCHAR(255) NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `senderId` BIGINT UNSIGNED NOT NULL, `receiverId` BIGINT UNSIGNED NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`senderId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`receiverId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Messages` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `MessageDeleteds` (`createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `messageId` BIGINT UNSIGNED , `deleterId` BIGINT UNSIGNED , PRIMARY KEY (`messageId`, `deleterId`), FOREIGN KEY (`messageId`) REFERENCES `Messages` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`deleterId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `MessageDeleteds` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `MessageUserBlockeds` (`createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `blockerId` BIGINT UNSIGNED , `blockedId` BIGINT UNSIGNED , PRIMARY KEY (`blockerId`, `blockedId`), FOREIGN KEY (`blockerId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`blockedId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `MessageUserBlockeds` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `Notifications` (`id` BIGINT UNSIGNED auto_increment , `type` ENUM('FOLLOWER', 'MESSAGE', 'LIKE', 'DISLIKE', 'COMMENT') NOT NULL, `postId` BIGINT UNSIGNED, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME, `userId` BIGINT UNSIGNED , `actorId` BIGINT UNSIGNED , PRIMARY KEY (`id`, `userId`, `actorId`), FOREIGN KEY (`postId`) REFERENCES `Posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`actorId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Notifications` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `PostFiles` (`id` BIGINT UNSIGNED auto_increment , `type` ENUM('PHOTO', 'VIDEO', 'PDF', 'FILE'), `url` VARCHAR(255) NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME, `postId` BIGINT UNSIGNED NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`postId`) REFERENCES `Posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `PostFiles` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `Reactions` (`id` BIGINT UNSIGNED auto_increment , `type` ENUM('like', 'dislike') NOT NULL, `objectType` ENUM('post', 'comment') NOT NULL, `objectTypeId` BIGINT UNSIGNED NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` BIGINT UNSIGNED NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Reactions` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `Interests` (`createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `categoryId` INTEGER UNSIGNED , `userId` BIGINT UNSIGNED , PRIMARY KEY (`categoryId`, `userId`), FOREIGN KEY (`categoryId`) REFERENCES `Categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Interests` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `PostSaved` (`createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `postId` BIGINT UNSIGNED , `userId` BIGINT UNSIGNED , PRIMARY KEY (`postId`, `userId`), FOREIGN KEY (`postId`) REFERENCES `Posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `PostSaved` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `Followers` (`createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `followerId` BIGINT UNSIGNED , `followedId` BIGINT UNSIGNED , PRIMARY KEY (`followerId`, `followedId`), FOREIGN KEY (`followerId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`followedId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Followers` FROM `zhowit`
Executing (default): CREATE TABLE IF NOT EXISTS `MessageContacts` (`createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `contactId` BIGINT UNSIGNED , `userId` BIGINT UNSIGNED , PRIMARY KEY (`contactId`, `userId`), FOREIGN KEY (`contactId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `MessageContacts` FROM `zhowit`